apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tfcu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ytex-tenant/rhtap-demo-app/hacbs-test-project-tfcu@sha256:fd7e723baad4b7e031b77766fee3e86d8d413749b1b52766926dc273d447434e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
