apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tfcu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ytex-tenant/rhtap-demo-app/hacbs-test-project-tfcu@sha256:ec93f83f0b90b6ae989a14c5fb844d8ce618e239dddabec06cacb1dfc6bdb46a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
